airflow-init:
  <<: *airflow-common
  container_name: airflow-init
  entrypoint: /opt/airflow/scripts/airflow-init.sh
  volumes:
    - ../dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ..:/opt/airflow/maritime-rl
    - ./airflow-init.sh:/opt/airflow/scripts/airflow-init.sh
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    airflow-postgres:
      condition: service_healthy
  networks:
    - maritime-network 